@startuml AudioSm

    '############################ States ############################

    [*] --> IDLE

    state IDLE
    state LOADING
    state PLAYING
    state PAUSED
    state TEXT_DISPLAYED

    '############################ Handlers ############################

    IDLE: enter / resetAllAudio(); uiIdle(); hideLoadingAnimation();
    IDLE --> LOADING : FORM_SUBMITTED [inputNotEmpty()] / startNewStoryProcess();
    IDLE --> LOADING : PLAY_BTN_CLICKED [inputNotEmpty()] / startNewStoryProcess();

    LOADING: enter / showLoadingAnimation(); uiPlayingButtons();
    LOADING --> PLAYING : SPEECH_READY
    LOADING --> IDLE : CANCEL / abortProcess(); pauseAllAudio(); resetAllAudio();

    PLAYING: enter / uiPlayingButtons(); redDots(); resetAllAudio(); setupAndStartAllAudio();
    PLAYING --> PAUSED : PLAY_BTN_CLICKED / pauseAllAudio();
    PLAYING --> LOADING : [inputNotEmpty()] / startNewStoryProcess();
    PLAYING --> IDLE : CANCEL / abortProcess(); pauseAllAudio(); resetAllAudio();
    PLAYING --> PLAYING : REPLAY_BTN_CLICKED / resumeAudioPosition(); resumeAllAudio();

    PAUSED: enter / uiPausedButtons(); addBlur();
    PAUSED --> PLAYING : PLAY_BTN_CLICKED / resumeAllAudio();
    PAUSED --> PLAYING : REPLAY_BTN_CLICKED / replay();
    PAUSED --> IDLE : CANCEL

/'! $CONFIG : toml
SmRunnerSettings.transpilerId = "JavaScript"
'/
@enduml
