@startuml AudioStateMachine

    '############################ States ############################

    [*] --> IDLE

    state IDLE
    state READY
    state LOADING
    state PLAYING
    state PAUSED

    '############################ Handlers ############################

    IDLE: enter / this.actions.pauseAllAudio(); this.actions.resetAllAudio(); this.actions.uiIdle(); this.actions.hideLoadingAnimation(); this.actions.initInputAdjustments();
    IDLE --> LOADING : SQUARE_CLICKED / this.actions.startNewStoryProcess();
    IDLE --> LOADING : FORM_SUBMITTED / this.actions.startNewStoryProcessForm();
    IDLE : VIEW_TOGGLED / this.actions.toggleView();
    IDLE : VIEW_TOGGLED [this.actions.getIsGridVisible] / this.actions.dotsViewTitle();
    IDLE : INPUT_CHANGED / this.actions.uiReadyButtons();

    LOADING: enter / this.actions.showLoadingAnimation(); this.actions.loadingDots(); this.actions.uiLoadingButtons(); this.actions.toggleView();
    LOADING --> PLAYING : SPEECH_READY / this.actions.setUpAndStartAllAudio();
    LOADING --> PAUSED : TOGGLE_PAUSE_RESUME / this.actions.pauseAllAudio();
    LOADING --> IDLE : CANCEL / this.actions.abortProcess();
    LOADING : VIEW_TOGGLED / this.actions.toggleView();
    LOADING : VIEW_TOGGLED [this.actions.getIsGridVisible] / this.actions.dotsViewTitle();
    LOADING : INPUT_CHANGED / this.actions.uiReadyButtons();

    PLAYING: enter / this.actions.uiPlayingButtons(); this.actions.removeBlurr(); this.actions.greenDots();
    PLAYING --> PAUSED : TOGGLE_PAUSE_RESUME / this.actions.pauseAllAudio();
    PLAYING --> IDLE : MUSIC_OVER [this.actions.bothTracksEnded()]
    PLAYING --> LOADING : SQUARE_CLICKED / this.actions.startNewStoryProcess();
    PLAYING --> LOADING : FORM_SUBMITTED / this.actions.startNewStoryProcessForm();
    PLAYING --> IDLE: CANCEL / this.actions.stopAndResetAllAudio();
    PLAYING : CHAT_HISTORY_CLICKED / this.actions.toggleTextVisibility();
    PLAYING : FROM_START_CLICKED / this.actions.pauseAllAudio(); this.actions.resetAllAudio(); this.actions.setUpAndStartAllAudio();
    PLAYING : SPEECH_OVER [!this.actions.getIsGridVisible()] / this.actions.toggleView();
    PLAYING : VIEW_TOGGLED / this.actions.toggleView();
    PLAYING : VIEW_TOGGLED [this.actions.getIsGridVisible] / this.actions.dotsViewTitle();
    PLAYING : INPUT_CHANGED / this.actions.uiReadyButtons();

    PAUSED: enter / this.actions.uiPausedButtons(); this.actions.addBlurr();
    PAUSED --> LOADING : SQUARE_CLICKED / this.actions.startNewStoryProcess();
    PAUSED --> PLAYING : TOGGLE_PAUSE_RESUME / this.actions.resumeAllAudio();
    PAUSED --> PLAYING : FROM_START_CLICKED / this.actions.resetAllAudio(); this.actions.setUpAndStartAllAudio();
    PAUSED --> IDLE: CANCEL / this.actions.setUpAndStartAllAudio();
    PAUSED : VIEW_TOGGLED / this.actions.toggleView();
    PAUSED : VIEW_TOGGLED [this.actions.getIsGridVisible] / this.actions.dotsViewTitle();
    PAUSED : INPUT_CHANGED / this.actions.uiReadyButtons();

/'! $CONFIG : toml
SmRunnerSettings.transpilerId = "JavaScript"
'/

@enduml
