@startuml AudioStateMachine

    '############################ States ############################

    [*] --> IDLE

    state IDLE
    state READY_DURING_IDLE
    state READY_DURING_PLAYBACK
    state READY_DURING_PAUSED
    state LOADING
    state PLAYING
    state PAUSED

    '############################ Handlers ############################

    IDLE: enter / this.actions.abortProcess(); this.actions.dotsView(); this.actions.pauseAllAudio(); this.actions.resetAllAudio(); this.actions.uiIdleButtons(); this.actions.initInputAdjustments();
    IDLE --> READY_DURING_IDLE : INPUT_CHANGED

    READY_DURING_IDLE: enter / this.actions.uiReadyButtons();
    READY_DURING_IDLE --> LOADING : SQUARE_CLICKED [this.actions.squareHasTitle()] / this.actions.startNewStoryProcessForm();
    READY_DURING_IDLE --> LOADING : FORM_SUBMITTED / this.actions.startNewStoryProcessForm();
    READY_DURING_IDLE --> LOADING : TOGGLE_PAUSE_RESUME / this.actions.startNewStoryProcessForm();
    READY_DURING_IDLE --> IDLE : INPUT_DEFOCUSED [!this.actions.getIsChatVisible()]
    READY_DURING_IDLE --> IDLE : CANCEL

    READY_DURING_PLAYBACK: enter / this.actions.uiReadyButtons();
    READY_DURING_PLAYBACK --> LOADING : SQUARE_CLICKED [this.actions.squareHasTitle()] / this.actions.startNewStoryProcessForm();
    READY_DURING_PLAYBACK --> LOADING : FORM_SUBMITTED / this.actions.startNewStoryProcessForm();
    READY_DURING_PLAYBACK --> LOADING : TOGGLE_PAUSE_RESUME / this.actions.startNewStoryProcessForm();
    READY_DURING_PLAYBACK --> PLAYING : INPUT_DEFOCUSED
    READY_DURING_PLAYBACK --> IDLE : CANCEL

    READY_DURING_PAUSED: enter / this.actions.uiReadyButtons();
    READY_DURING_PAUSED --> LOADING : SQUARE_CLICKED [this.actions.squareHasTitle()] / this.actions.startNewStoryProcessForm();
    READY_DURING_PAUSED --> LOADING : FORM_SUBMITTED / this.actions.startNewStoryProcessForm();
    READY_DURING_PAUSED --> LOADING : TOGGLE_PAUSE_RESUME / this.actions.startNewStoryProcessForm();
    READY_DURING_PAUSED --> PAUSED : INPUT_DEFOCUSED
    READY_DURING_PAUSED --> IDLE : CANCEL

    LOADING: enter / this.actions.uiLoadingButtons(); this.actions.removeBlurr(); this.actions.dotsView(); this.actions.redDots();
    LOADING --> PLAYING : SPEECH_READY / this.actions.setUpAndStartAllAudio(); this.actions.displayStoryText(); this.actions.wrapWordsInSpans();
    LOADING --> PAUSED : TOGGLE_PAUSE_RESUME / this.actions.pauseAllAudio();
    LOADING --> IDLE : CANCEL

    PLAYING: enter / this.actions.uiPlayingButtons(); this.actions.removeBlurr(); this.actions.greenDots();
    PLAYING --> PAUSED : TOGGLE_PAUSE_RESUME / this.actions.pauseAllAudio();
    PLAYING --> READY_DURING_PLAYBACK : INPUT_CHANGED
    PLAYING --> IDLE : MUSIC_OVER [this.actions.bothTracksEnded()] / this.actions.resetAllAudio(); this.actions.uiIdleButtons();
    PLAYING --> IDLE : CANCEL
    PLAYING : FROM_START_CLICKED / this.actions.pauseAllAudio(); this.actions.resetAllAudio(); this.actions.setUpAndStartAllAudio();
    PLAYING : SPEECH_OVER / this.actions.addTitleToSquare(); this.actions.textView();

    PAUSED: enter / this.actions.uiPausedButtons(); this.actions.addBlurr();
    PAUSED --> READY_DURING_PAUSED : INPUT_CHANGED
    PAUSED --> PLAYING : TOGGLE_PAUSE_RESUME / this.actions.resumeAllAudio();
    PAUSED --> PLAYING : FROM_START_CLICKED / this.actions.resetAllAudio(); this.actions.setUpAndStartAllAudio();
    PAUSED --> IDLE: CANCEL

/'! $CONFIG : toml
SmRunnerSettings.transpilerId = "JavaScript"
'/

@enduml
