@startuml AudioStateMachine

    '############################ States ############################

    [*] --> IDLE

    state IDLE
    state READY
    state LOADING
    state PLAYING
    state PAUSED
    state TEXT_DISPLAYED

    '############################ Handlers ############################

    IDLE: enter / this.actions.pauseAllAudio(); this.actions.resetAllAudio(); this.actions.uiIdle(); this.actions.hideLoadingAnimation(); this.actions.initInputAdjustments();
    IDLE --> READY : INPUT_CHANGED [this.actions.inputIsValid()]

    READY: enter / this.actions.uiReadyButtons();
    READY --> LOADING : FORM_SUBMITTED / this.actions.startNewStoryProcess();
    READY --> LOADING : PLAY_PAUSE_CLICKED / this.actions.startNewStoryProcess();
    READY --> IDLE : INPUT_CHANGED [this.actions.inputIsEmpty()]

    LOADING: enter / this.actions.showLoadingAnimation(); this.actions.uiLoadingButtons();
    LOADING --> PLAYING : SPEECH_READY / this.actions.updateStoryText(); this.actions.setUpAndStartAllAudio();
    LOADING --> PAUSED : PLAY_PAUSE_CLICKED / this.actions.pauseAllAudio();
    LOADING --> IDLE : CANCEL / this.actions.abortProcess();

    PLAYING: enter / this.actions.uiPlayingButtons(); this.actions.removeBlurr(); this.actions.redDots();
    PLAYING --> PAUSED : SPACEBAR_TOGGLE_PAUSE_RESUME / this.actions.pauseAllAudio();
    PLAYING --> PAUSED : PLAY_PAUSE_CLICKED / this.actions.pauseAllAudio();
    PLAYING --> IDLE : MUSIC_OVER
    PLAYING --> READY : INPUT_CHANGED [this.actions.inputIsValid()]
    PLAYING : CHAT_HISTORY_CLICKED / this.actions.toggleTextVisibility();
    PLAYING : FROM_START_CLICKED / this.actions.pauseAllAudio(); this.actions.resetAllAudio(); this.actions.setUpAndStartAllAudio();

    PAUSED: enter / this.actions.uiPausedButtons(); this.actions.addBlurr();
    PAUSED --> PLAYING : SPACEBAR_TOGGLE_PAUSE_RESUME / this.actions.resumeAllAudio();
    PAUSED --> PLAYING : PLAY_PAUSE_CLICKED / this.actions.resumeAllAudio();
    PAUSED --> PLAYING : FROM_START_CLICKED / this.actions.resetAllAudio(); this.actions.setUpAndStartAllAudio();
    PAUSED --> READY : INPUT_CHANGED [this.actions.inputIsValid()]
    PAUSED : FROM_START_CLICKED / this.actions.resetAllAudio();


/'! $CONFIG : toml
SmRunnerSettings.transpilerId = "JavaScript"
'/

@enduml
