name: Build & Deploy to Scaleway

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Login to Scaleway Container Registry
      uses: docker/login-action@v3
      with:
        username: nologin
        password: ${{ secrets.SCALEWAY_API_KEY }}
        registry: ${{ secrets.CONTAINER_REGISTRY_ENDPOINT }}
    - name: Build the Docker image
      run: docker build . -t ${{ secrets.CONTAINER_REGISTRY_ENDPOINT }}/teller-image
    - name: Push the Docker Image
      run: docker push ${{ secrets.CONTAINER_REGISTRY_ENDPOINT }}/teller-image
    - name: Install Scaleway CLI
      run: |
        curl -s https://raw.githubusercontent.com/scaleway/scaleway-cli/main/scripts/install.sh | bash
        echo "$HOME/.local/bin" >> $GITHUB_PATH
    - name: Deploy to Scaleway
      run: |
        scw init --api-key ${{ secrets.SCALEWAY_API_KEY }}
        scw serverless container deploy ${{ secrets.CONTAINER_ID }}
          --env "USE_BUCKET=${{ vars.USE_BUCKET }}"
          --env "BUCKET_NAME=${{ vars.BUCKET_NAME }}"
          --env "BUCKET_ENDPOINT=${{ vars.BUCKET_ENDPOINT }}"
          --secret "BUCKET_ACCESS_KEY=${{ secrets.BUCKET_ACCESS_KEY }}"
          --secret "BUCKET_SECRET_KEY=${{ secrets.BUCKET_SECRET_KEY }}"
          --secret "SCALEWAY_API_KEY=${{ secrets.SCALEWAY_API_KEY }}"
          --secret "CONTAINER_REGISTRY_ENDPOINT=${{ secrets.CONTAINER_REGISTRY_ENDPOINT }}"
          --secret "MISTRAL_API_KEY=${{ secrets.MISTRAL_API_KEY }}"
          --secret "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}"
          --secret "ELEVENLABS_API_KEY=${{ secrets.ELEVENLABS_API_KEY }}"
          --secret "NEWSAPI_API_KEY=${{ secrets.NEWSAPI_API_KEY }}"
